
// This file has been generated by the GUI designer. Do not modify.
namespace JLWidgets
{
	public partial class IconLabel
	{
		private global::Gtk.Alignment alignment2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Image image;

		private global::Gtk.Label label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget JLWidgets.IconLabel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "JLWidgets.IconLabel";
			// Container child JLWidgets.IconLabel.Gtk.Container+ContainerChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.image.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.hbox5.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label");
			this.hbox5.Add (this.label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.alignment2.Add (this.hbox5);
			this.Add (this.alignment2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
