
// This file has been generated by the GUI designer. Do not modify.
namespace LampManager
{
	public partial class AboutDialog
	{
		private global::Gtk.Notebook notebook4;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Image image1356;

		private global::Gtk.Label label17;

		private global::Gtk.Label label15;

		private global::Gtk.ScrolledWindow scrolledwindow4;

		private global::Gtk.TextView textview3;

		private global::Gtk.Label label16;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LampManager.AboutDialog
			this.Name = "LampManager.AboutDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("About...");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("LampManager.tray.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Internal child LampManager.AboutDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook4 = new global::Gtk.Notebook ();
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 0;
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.image1356 = new global::Gtk.Image ();
			this.image1356.Name = "image1356";
			this.image1356.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("LampManager.lamp-manager-splash.png");
			this.vbox5.Add (this.image1356);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.image1356]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("v. 0.1.4a");
			this.vbox5.Add (this.label17);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label17]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.notebook4.Add (this.vbox5);
			// Notebook tab
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("About");
			this.notebook4.SetTabLabel (this.vbox5, this.label15);
			this.label15.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView ();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.scrolledwindow4.Add (this.textview3);
			this.notebook4.Add (this.scrolledwindow4);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4[this.scrolledwindow4]));
			w6.Position = 1;
			// Notebook tab
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Credits");
			this.notebook4.SetTabLabel (this.scrolledwindow4, this.label16);
			this.label16.ShowAll ();
			w1.Add (this.notebook4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1[this.notebook4]));
			w7.Position = 0;
			// Internal child LampManager.AboutDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8[this.buttonOk]));
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 522;
			this.DefaultHeight = 529;
			this.Show ();
			this.buttonOk.Activated += new global::System.EventHandler (this.OnButtonOkActivated);
		}
	}
}
