
// This file has been generated by the GUI designer. Do not modify.
namespace LampManager
{
	public partial class ApachePanel
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Label statusLabel1;

		private global::Gtk.Label versionLabel;

		private global::Gtk.Label label5;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Notebook notebook1;

		private global::LampManager.ApacheModsList apacheModsList;

		private global::Gtk.Label label3;

		private global::LampManager.ApacheSitesList apacheSitesList;

		private global::Gtk.Label label4;

		private global::LampManager.ApacheStatusPanel apachestatuspanel1;

		private global::Gtk.Label label6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LampManager.ApachePanel
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "LampManager.ApachePanel";
			// Container child LampManager.ApachePanel.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Status:</b>");
			this.label1.UseMarkup = true;
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.statusLabel1 = new global::Gtk.Label ();
			this.statusLabel1.Name = "statusLabel1";
			this.statusLabel1.LabelProp = "label2";
			this.hbox1.Add (this.statusLabel1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.statusLabel1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.versionLabel = new global::Gtk.Label ();
			this.versionLabel.Name = "versionLabel";
			this.versionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.versionLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.versionLabel]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Version:</b>");
			this.label5.UseMarkup = true;
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label5]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.apacheModsList = new global::LampManager.ApacheModsList ();
			this.apacheModsList.Events = ((global::Gdk.EventMask)(256));
			this.apacheModsList.Name = "apacheModsList";
			this.notebook1.Add (this.apacheModsList);
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Mods");
			this.notebook1.SetTabLabel (this.apacheModsList, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.apacheSitesList = new global::LampManager.ApacheSitesList ();
			this.apacheSitesList.Events = ((global::Gdk.EventMask)(256));
			this.apacheSitesList.Name = "apacheSitesList";
			this.notebook1.Add (this.apacheSitesList);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.apacheSitesList]));
			w10.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Sites");
			this.notebook1.SetTabLabel (this.apacheSitesList, this.label4);
			this.label4.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.apachestatuspanel1 = new global::LampManager.ApacheStatusPanel ();
			this.apachestatuspanel1.Events = ((global::Gdk.EventMask)(256));
			this.apachestatuspanel1.Name = "apachestatuspanel1";
			this.notebook1.Add (this.apachestatuspanel1);
			global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.apachestatuspanel1]));
			w11.Position = 2;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
			this.notebook1.SetTabLabel (this.apachestatuspanel1, this.label6);
			this.label6.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
			w12.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
