
// This file has been generated by the GUI designer. Do not modify.
namespace LampManager
{
	public partial class PHPPanel
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action editAction;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label11;

		private global::Gtk.Label versionLabel;

		private global::Gtk.Notebook notebook3;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.TextView infoTextView;

		private global::Gtk.Label label10;

		private global::Gtk.Toolbar toolbar2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LampManager.PHPPanel
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Editar php.ini"), null, "gtk-edit");
			this.editAction.IsImportant = true;
			this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar php.ini");
			w2.Add (this.editAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "LampManager.PHPPanel";
			// Container child LampManager.PHPPanel.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(9));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Version:</b>");
			this.label11.UseMarkup = true;
			this.hbox3.Add (this.label11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label11]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.versionLabel = new global::Gtk.Label ();
			this.versionLabel.Name = "versionLabel";
			this.versionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label12");
			this.hbox3.Add (this.versionLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.versionLabel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook3 = new global::Gtk.Notebook ();
			this.notebook3.CanFocus = true;
			this.notebook3.Name = "notebook3";
			this.notebook3.CurrentPage = 0;
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.infoTextView = new global::Gtk.TextView ();
			this.infoTextView.CanFocus = true;
			this.infoTextView.Name = "infoTextView";
			this.infoTextView.Editable = false;
			this.scrolledwindow3.Add (this.infoTextView);
			this.notebook3.Add (this.scrolledwindow3);
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("PHPInfo");
			this.notebook3.SetTabLabel (this.scrolledwindow3, this.label10);
			this.label10.ShowAll ();
			this.vbox3.Add (this.notebook3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.notebook3]));
			w8.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='editAction' action='editAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.vbox3.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.toolbar2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.editAction.Activated += new global::System.EventHandler (this.OnEditPHPIni);
		}
	}
}
